### ISSUE TITLE
Make Synonyms in Spanish available

### ISSUE THREAD

**Issue by EhuddR** [phibr0/obsidian-dictionary#10]
Hello! First of all, excellent plugin, it has helped me a lot in the last week. I would like to have the possibility to use the Spanish synonyms provider. At the moment it is only available for English and French. 

Thank you very much.

**Comment by phibr0** [comment]
I will look into adding Spanish Support, if you know how to work with typescript maybe you add it yourself, look into the Readme for a "guide".
If not that of course totally fine too, but it will take me some time!

**Comment by EhuddR** [comment]
I don't know how to code in typescript, I checked your guide and although it looks simple I wouldn't know where to start.  Don't worry, take your time, I don't think it's easy to get an API for synonyms in Spanish.

Thanks in advance.
