### ISSUE TITLE
Any plan to make it work offline for English language ?

### ISSUE THREAD

**Issue by radha1990kumari** [phibr0/obsidian-dictionary#15]

**Comment by phibr0** [comment]
You can enable Caching in the Settings to get a semi-offline Experience. It will save every word you looked up while being online and when you ever look it up again you can do it while being offline.

To make it work completely offline we would need a full database of most words. I couldn't find one which is free.

**Comment by radha1990kumari** [comment]
@phibr0 ,what should be the format of the database , I will try to find it .

**Comment by phibr0** [comment]
The best would be plain JSON, but I guess i could work with most of them.

**Comment by iris2jane** [comment]
[Online Dictionary Helper (with Anki support)](https://github.com/ninja33/ODH)

**Comment by phibr0** [comment]
[dictionary.zip](https://github.com/phibr0/obsidian-dictionary/files/6881229/dictionary.zip)

Extracted the json File, will have to look into this sometime

**Comment by phibr0** [comment]
You can now select a offline Dictionary in the Settings for English and Chinese
