### ISSUE TITLE
'Pronunciation' and 'Meanings' not translated

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#16]
The headers 'Pronunciation' and 'Meanings' aren’t translated, and 'New Note' isn’t. All are in 'de.ts', for example.

**Comment by phibr0** [comment]
I currently can't check in App, could you provide Screenshots or just explain where exactly something isn't translated? As I am checking in the Code it should all be translated fine.

**Comment by Moonbase59** [comment]
Let’s take the phrases 'Pronunciation', 'Meanings' and 'New Note', which are used in the side panel and when generating a new note (for `{{pronunciationHeader}}` and `{{meaningHeader}}`.

Let’s also assume we’re using only English and German. The phrases _are_ correct in `de.ts` and also make it into the plugin’s `main.js`:

```javascript
    //dictionaryView.svelte
    'Enter a word': 'Gebe ein Wort ein',
    'Pronunciation': 'Aussprache',
    'Meanings': 'Bedeutungen',
    'New Note': 'Neue Notiz',
```

When setting Obsidian to German ("Deutsch"), the side panel still shows the English headings:

![Auswahl_052](https://user-images.githubusercontent.com/3706922/126482170-eb5de1d5-1b0f-4404-b3b5-e244ce85b93b.png)

When I click on 'New Note', the English headings are also used in the new note:

![Knowledgebase - Obsidian v0 12 10_053](https://user-images.githubusercontent.com/3706922/126482786-18761d86-8f7a-41ce-9466-66dffbca0c5b.png)

**Comment by phibr0** [comment]
These translations currently depend on Obsidians Language not on the API Language.

**Comment by phibr0** [comment]
The Language is set by Obsidians internal Moment Locale. You have set your Language to German which should turn the Plugins Language to German too. Are the Settings also all in English?

**Comment by Moonbase59** [comment]
The Obsidian settings are in German, those of non-translated plugins in English, yours also in English:

![Auswahl_056](https://user-images.githubusercontent.com/3706922/126494112-4c66d41d-76a9-4cc6-a2ed-399f30d45224.png)

Reminds me of an odd problem I had, and nobody found an answer for (I’m using the moment.js locale myself to check what language Obsidian runs in): https://forum.obsidian.md/t/new-with-0-12-4-moment-locale-sticks-at-en-even-when-i-switch-obsidian-to-another-language/19673

**Comment by Moonbase59** [comment]
Hm. If I enter

```javascript
moment().locale()
```

in the dev console, it gives me `en`. So maybe related, but for the life of me I can’t make out who or what messes with moment’s locale and sets it globally …

Let me try

```javascript
moment.locale("de")
```

and see what happens.

Still the same:

![Auswahl_052](https://user-images.githubusercontent.com/3706922/126495208-befa7405-8b93-41a1-8cae-07da4ed9b572.png)

**Comment by phibr0** [comment]
"Adjektiv" came as part of the API Response, not from the Plugin itself. Could you maybe try to disable all Plugins except the Dictionary Plugin? Or just create a Test Vault with only that Plugin installed.

**Comment by phibr0** [comment]
Also I am pretty sure that after setting the moment locale to de the View needs to be re-rendered to show changes in these Strings.

**Comment by Moonbase59** [comment]
Yep, I’ve later seen that it came from the API. Any idea how I could re-render the view?

I’ll try the plugin disable/new vault later on.

**Comment by phibr0** [comment]
I think just closing it (right click on the icon) and opening it again with the Command should work

**Comment by Moonbase59** [comment]
Got it! After disabling _all_ plugins except yours, …

- settings come up in German
- the side pane gets translated
- notes created have the German text*

So I must really dig in deeper to isolate the plugin that causes the locale mess-up. Sorry for bothering you with this!

* = There _is_ one untranslated string still: In the dictionary-generated note, Pronunciation has a list item `- undefined`. "Undefined" should probably also be translated.

![Knowledgebase - Obsidian v0 12 10_057](https://user-images.githubusercontent.com/3706922/126618355-0826ace2-7d70-473f-a792-c37bcfeb46e3.png)

Btw, thanks for making this really useful plugin, and actually taking care of translations—not many plugins do that.

**Comment by phibr0** [comment]
The `undefined` actually has to be a bug, it shouldn't print "Aussprache" if it doesn't have any data for it. 

I think the Calendar Plugin overrides the moment locale but I am not sure.

**Comment by Moonbase59** [comment]
Calendar: Yeah, someone mentioned that in the forums, but I’ve never used that. So there must be another miscreant ;-)

Doesn’t the note always contain _all_ information, if if there’s nothing in it? If not, we have another minor bug.

**Comment by phibr0** [comment]
Since this isn't really a Issue of this Plugin i will close this for now. The other Plugins which are localized also get the locale from moment which is why I think it's fine like that.

**Comment by Moonbase59** [comment]
Yep. I finally found the miscreant: It was the [Obsidian Pomodoro Plugin](https://github.com/tokuhirom/obsidian-pomodoro-plugin) that globally set the `moment` locale.
