### ISSUE TITLE
data.json: Cached definitions stored twice?

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#17]
It looks like the cached definitions in `data.json` are stored _twice_.

I attach my `data.json` so you can verify:
[data.json.zip](https://github.com/phibr0/obsidian-dictionary/files/6854210/data.json.zip)

Using Obsidian 0.12.10 (installer 0.12.10/AppImage) on Linux Mint 20.2, Dictionary v2.10.0.

**Comment by phibr0** [comment]
Does it happen all the time? Could you delete your Cache and look for if it happens again?

I will definitely have to sort this one out

**Comment by Moonbase59** [comment]
It seems to work correctly after deleting the cache. I’ll keep watching it.

Btw, when deleting the cache from settings, the number of cached items isn’t updated to show zero, so one is unsure if anything happened. Only after closing/reopening settings, it correctly shows zero.

**Comment by phibr0** [comment]
Found the Bug! I was missing a saveSettings call which then caused to create double Caches on Disk!

**Comment by phibr0** [comment]
Since this isn't really a Issue of this Plugin i will close this for now. The other Plugins which are localized also get the locale from moment which is why I think it's fine like that.

**Comment by Moonbase59** [comment]
Cool you found & fixed it! :+1:
