### ISSUE TITLE
When switching from English (US) to German from the side panel, no Synonym Provider Service can be selected

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#18]
Version 2.10.0, on Obsidian 0.12.10 (Linux AppImage):

When switching from English (US) to German from the side panel, no Synonym Provider Service can be selected:

![Auswahl_054](https://user-images.githubusercontent.com/3706922/126483744-c515fc6d-6d1d-42a3-8f5c-197410deb9b9.png)

One must then go to the plugin settings and choose one from there:

![Auswahl_055](https://user-images.githubusercontent.com/3706922/126483783-eb74f158-c72d-46bc-8400-74d641d2dd10.png)

![Auswahl_056](https://user-images.githubusercontent.com/3706922/126483809-62551824-d3c2-4f04-acb8-d4e478d76dca.png)

**Comment by phibr0** [comment]
That's a Issue i already found, but I couldn't find the reason for why it exists. I can fix the Problem in the Settings, but the Problem with the Modal still persists. Once you type a character the Options will show and you can select one of them.

**Comment by Moonbase59** [comment]
Without peeking in the code, could it be because it wants to find (and initially display) the _current_ setting, in this case `Free Dictionary API`, which _isn’t_ in the list for Germany (`OpenThesaurus`, `Altervista`)?

**Comment by phibr0** [comment]
Yeah that's the Problem for the Settings Tab. I am not sure if that's also the Problem for the Modal but I will look into that

**Comment by Moonbase59** [comment]
I guess yes, skimming through the code yesterday I saw that you compare somewhere … Let me see if I can find the source again …

[This](https://github.com/phibr0/obsidian-dictionary/blob/ad7f8ba6ede8c6eb91538484b56f4fee6fe62114/src/ui/modals/synonymProviderChooser.ts#L20-L24) doesn’t make sense to me.

`onChooseItem` will only ever be used if the list has zero or one entries, but for Germany the list has _two_ entries (OpenThesaurus and Altervista). Probably just use `.first()` and the nullish coalescing without the `if`, like in

```typescript
    onOpen(): void {
        this.onChooseItem(this.available.first() ?? "");
    }
```

**Comment by Moonbase59** [comment]
Nope …

**Comment by phibr0** [comment]
Yeah that code is there, so that if only one option exists for your language you can't choose.

**Comment by Moonbase59** [comment]
I can’t for the life of me not make out why the LanguageChooser _always_ shows the selections while the DefinitionProviderChooser and SynonymProviderChooser don’t. They all extend the FuzzySuggestModal, the only difference being that the latter ones are instantiated in the `async onChooseItem` of their former ones, and `.open()` called.

I wonder if `.open()` might behave differently, or it’s simply a timing issue (since `onChooseItem` is async).

**Comment by phibr0** [comment]
Thanks for the debugging! That's exactly what I found which is also why it's still like that as today

**Comment by Moonbase59** [comment]
Well, thanks for investigating, maybe someone on the Discord has an idea. Or they messed something up ;-)
