### ISSUE TITLE
Can't get any results

### ISSUE THREAD

**Issue by Archie-2021** [phibr0/obsidian-dictionary#19]
First of all. Thanks for this great plugin.

I can't get any results when highlighting a text. I works when I search for the stuff on the right pane. Is there anything else I should enable. The synonym suggestion is enabled so I don't know what else I should change

P.s. it is working inside the created notes for words. It is just not working on the rest of the vault

**Comment by phibr0** [comment]
Did you set the correct Language in the Settings?

**Comment by phibr0** [comment]
I will close this for now.
