### ISSUE TITLE
Error: File already exists when trying to make a new note

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#20]
This is one to think about: Let’s take the word 'human'. In English, this can be a noun as well as an adjective, in German it’s an adjective.

I’m bilingual and switch between English and German quite a lot, so it sometimes happens a word is in _both_ languages, but I still want to make a note of it. When trying this with 'human', the plugin detects the file `Human.md` already present in my `Dictionary` folder and simply gives an error message `Error: File already exists`.

This poses two problems:

- What if I wish to _overwrite_ the original with a new version (say, from another synonym provider)?
- How to distinguish dictionary notes _in multiple languages?_

I’d propose the following solutions:

- **For existing notes in the dictionary folder**, either
  - overwrite the existing file (potentially dangerous if someone manually edited it!), or
  - show a modal asking if it should be overwritten.
- **For multiple language dictionaries**:
  - Let the user _template_ the dictionary name. So _if_ she wanted the dictionary split into multiple language Dictionaries, maybe use something like `Dictionary ({{language}})` and fill in the _currently selected dictionary language_ upon note creation. This would then use folder names like `Dictionary (German)` or `Dictionary (English (US))`, in my example.
    Since the two-letter ISO 639 and [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) codes are quite popular, these might also be used and generate something like `Dictionary (en-US)` or `Dictionary (de-DE)`. Maybe even with a second template variable like `{{lang}}` or something?
    If no template variable was used in the dictionary name, assume a "one-for-all" folder. This would be the case for most users that only use one language.

**Comment by phibr0** [comment]
These are good improvements. I will start working on these next week!

**Comment by Moonbase59** [comment]
Well, not  bad idea. I totally forgot about the prefix and suffix possibilities. So we can at least have _one_ dictionary with the entries sorted. I’ll probably use it as a prefix, though. Good you replace it in there, too ;-)
