### ISSUE TITLE
Suggestion for adding the link to pronunciation audio file to the template

### ISSUE THREAD

**Issue by Archie-2021** [phibr0/obsidian-dictionary#21]
I like to connect this notes to my Anki database via obsidian to Anki plugin. This would help to this end

Thanks

**Comment by Moonbase59** [comment]
This could be useful, I agree.

There are three possible ways the generated code could look like, these should be somehow selectable in settings, I think:

- a **raw Markdown-type link** (will open external default player on click):
  - `<https://lex-audio.useremarkable.com/mp3/minute_us_1.mp3>`
- a real **Markdown link** (will open external default player on click):
  - `[Audio](https://lex-audio.useremarkable.com/mp3/minute_us_1.mp3)`
  - (the word "Audio" should be settable, users might want "Listen" or something)
- an actual **HTML `<audio>` element**, so it can be directly played in Obsidian and other Markdown-capable software:
  - ```
    <audio controls>
      <source src="https://lex-audio.useremarkable.com/mp3/minute_us_1.mp3" type="audio/mpeg">
    </audio>
    ```

![Knowledgebase - Obsidian v0 12 10_058](https://user-images.githubusercontent.com/3706922/126624745-3b31a450-c134-441d-9b16-0a6039d09ea3.png)

**Comment by phibr0** [comment]
You can embed Audio Files in Obsidian using ![[file.mp3]], does this also work with a url?

**Comment by Moonbase59** [comment]
Nope, unfortunately not. There some FRs for that, but currently it doesn’t work with external URIs.

**Comment by phibr0** [comment]
I asked the Devs about why this isn't working, still waiting for a response though

**Comment by phibr0** [comment]
I think I have a pretty good solution ready! If audio is present in the API Response the Note will now contain the following:

When opening the Note:

![image](https://user-images.githubusercontent.com/59741989/126814390-6d33787a-7af7-4b4b-ab0f-e8a69449625c.png)

When clicking on the Text:

![image](https://user-images.githubusercontent.com/59741989/126814445-c00f0b02-9ebd-41fd-a6e3-7dc11f5952c6.png)

This is achieved through the following markup:

```html
<details><summary>Obsidián</summary><audio controls><source src="https://lex-audio.useremarkable.com/mp3/minute_us_1.mp3" type="audio/mpeg"></audio></details>
```

**Comment by Moonbase59** [comment]
This looks like a nice solution, yes! Just don’t fix the audio type to "audio/mpeg", there might be some services that return Ogg, Ogg Vorbis, WAV or FLAC. (But they’ll probably also specify the type.)

**Comment by Moonbase59** [comment]
It’s not in 2.11.0 yet, correct?

![Knowledgebase - Obsidian v0 12 10_061](https://user-images.githubusercontent.com/3706922/126879241-752acb02-3a6a-4834-a4ba-3e1f410f2560.png)

**Comment by Archie-2021** [comment]
Thanks for implemeting this but it is still not working well with Anki. Please separate the link and phonetic clearly in the template. Anki can auto play the audio and right now I have to open the folded audio in hit play manually which is not quick altho it looks better. Aslo Anki can extract the audio files locally if it gets only the link. So I think if you let more flexibility in the template would be awesome.

Thanks again for your effort. I really appreciate it

**Comment by phibr0** [comment]
You can now use the `{{audioLinks}}` Variable in your Template

**Comment by Archie-2021** [comment]
Well That was very quick and awesome. Thanks
