### ISSUE TITLE
In _constants.ts, LANGUAGE codes shouldn’t be mixed

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#22]
In [`_constants.ts`](https://github.com/phibr0/obsidian-dictionary/blob/83b42344d01e666333fb8643a9671f2c156bc58d/src/_constants.ts#L8), there is a mixture of codes for language, like

```javascript
    "en_US": "English (US)",
    "en_GB": "English (UK)",
    "pt-BR": "Brazilian Portuguese",
```

Some are using an underscore `_` as separator between _language_ and _country_, some use a hyphen `-`. Although some OSes use the underscore, I’d suggest using [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646) codes instead (those with a hyphen).

For non-English speakers it might also be nice to use localized language names, like the Obsidian language selector does. Example:

```javascript
export const LANGUAGES = {
    "en_US": "English (US)",
    "hi": "हिन्दी",
    "es": "Español",
    "fr": "Français",
    "ja": "日本語",
    "ru": "Русский",
    "en_GB": "English (UK)",
    "de": "Deutsch",
    "it": "Italiano",
    "ko": "한국어 (韓國語), 조선말 (朝鮮語)",
    "pt-BR": "Português do Brasil",
    "ar": "اَلْعَرَبِيَّةُ‎",
    "tr": "Türkçe"
}
```

**Comment by phibr0** [comment]
Looks good, would you like to open a PR for this? Also changing the way the Language Codes are handled might bring issues with already existing caches.

**Comment by Moonbase59** [comment]
Sure, caches might be corrupted. Plus, I don’t know if any upstream code or APIs already use the "wrong" language codes. I suspect at least the Free Dictionary API might.

Haven’t done PRs for ever so long, and I’m not too fluent with Typescript/Javascript, so I fear I might mess things up, especially since I’m quite short on time currently. Maybe I should better leave it to you, since you know your code much better …

**Comment by Moonbase59** [comment]
Just for the fun of it: If I _was_ to try a PR, how would the build environment look like (i.e., what’s to install on a Linux, Debian-type, system)? And how to build (in order to test the changes before making a PR)?

Is there any good documention for building Typescript Obsidian plugins you could link me to?

**Comment by phibr0** [comment]
You can read about how to get started here: https://github.com/obsidianmd/obsidian-sample-plugin

There currently isn't much documentation (it will probably come after Obsidian 1.0) except the Obsidian Definition File https://github.com/obsidianmd/obsidian-api . If  you need help your best bet will be the Obsidian Discord, which you can find on their Website.

**Comment by Moonbase59** [comment]
Thanks for these! If I get some spare time, I’ll give it a spin …

**Comment by phibr0** [comment]
The Languages Codes are like that because initially the Plugin was only using the https://freedictionaryapi.dev which was using these Codes. I agree that this is pretty unfortunate and I will fix this too.
