### ISSUE TITLE
When activating the plugin, "DevTools failed to load SourceMap …"

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#23]
When activating the plugin in a fresh vault, I get in the Dev Console:

```text
VM203:4243 loading dictionary
DevTools failed to load SourceMap: Could not parse content for app://obsidian.md/main.js.map: Unexpected end of JSON input
```

It seems to work nevertheless, but the warning is somehow disturbing …

**Comment by phibr0** [comment]
This isn't a Error it's just a warning. When transpiling the TS to JS normally a Sourcemap is added for easier debugging. I deactivated this Behaviour to decrease the file size of the main.js output. But now that I think of it this should only be done in Release mode not for developing.
