### ISSUE TITLE
Suggestion: Use separate file for the cache, reduce size

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#25]
Just a suggestion: If one uses definition caching, the cache grows _rapidly_, even after the fix not to double-cache. I don’t think it’s wise to keep all this together with the plugin settings in `data.json`.

Instead, I propose to use a separate `cache.json`, which would also make the deleting of the cache much easier.

The data file currently uses a lot of space because it is "pretty" JSON. I don’t think users will ever manually edit it, so I also propose to use something like `JSON.stringify()` to make it more compact and faster loading.

How do you feel about that?

**Comment by phibr0** [comment]
That's a good improvement. I will have to look into how this would be handled on mobile though

**Comment by Moonbase59** [comment]
Man, you’re progressing at a fast pace! :heart_eyes: :+1:
