### ISSUE TITLE
Migrate to new request API instead of using fetch + cors proxy

### ISSUE THREAD

**Issue by phibr0** [phibr0/obsidian-dictionary#27]
Migrate to Obsidians new request API.

https://forum.obsidian.md/t/obsidian-release-v0-12-11-insider-build/21184/2

**Comment by phibr0** [comment]
Every API except the Systran API are now migrated to use the new request API. Systran requires headers for authentication, which currently cannot be set when using request.

Commits:

2369a895795e7498b569e8f7f6098d9e4f8bc165
56c4bbeaaf9ad934c586c3c1aa2db5cba257d68b
96cebbb56b0104378696b0d2e8b9bd7fd1b353d8
efdedbabde659b4e61a11e9a82e47ce9a00cea06

**Comment by Moonbase59** [comment]
Good move. Only please don’t require Obsidian 0.12.11 yet … not everyone has the insider builds.

**Comment by phibr0** [comment]
Since Systran doesn't work anymore and thus was removed, this can be closed
