### ISSUE TITLE
Support auto look up in sidebar

### ISSUE THREAD

**Issue by wenlzhang** [phibr0/obsidian-dictionary#30]
Currently, one may double-click a word, then its synonym would automatically show up in a list below the selected word. Similarly, is it possible to autofill in the selected word in the sidebar (maybe also automatically expand the dictionary sidebar), to be able to automatically look up the word? This way, one may not need to type the word again in the sidebar.

In case that there are users do not want this auto lookup feature, this can be an option in the configuration pane of the plugin.

**Comment by Moonbase59** [comment]
Just right-click the marked word and select "look up" ;-)

**Comment by wenlzhang** [comment]
My bad. Forgot to enable the option "Show Options in Context Menu" in the configuration pane. 😅
