### ISSUE TITLE
Case-insensitive lookup?

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#31]
I know this might not always make sense, but I often run into lookup cases like "Human" which the lookup doesn’t find (although the context menu shows synonyms).

Using the English dictionary, try looking up

- "Human" → nothing found
- "human" → found

_If_ case-insensitive lookup was added, it should follow the usual Unicode rules, because we’ve got too many languages where a simple "ASCII" upper-/lowercase will fail. Don’t know how far JS is in that respect.

**Comment by phibr0** [comment]
Again this depends on the API. I could just change it to always search for lowercase words.

Which API were you using?

**Comment by Moonbase59** [comment]
In that case, English (US) Freed Dictionary API for both defs & synonyms.
But I also use German (Free Dictionary for defs and both OpenThesaurus and Altervista for synonyms).

Wonder if the "lowercasing" on your end would work, there _might_ be words with a different lookup if changing the case. Seems at least in FreeDict/OpenThesaurus they’re stored with their "correct" capitalization, i.e. in English, you won’t find "Human" (but it might well start a sentence and thus be capitalized!) but "human" as a noun, while in German you’d only find "human" (not "Human") as an adjective.

Difficult one, this.

**Comment by Moonbase59** [comment]
Pure lowercasing will _not_ work. Just checked "Wörterbuch" ("dictionary") in Free Dictionary API/OpenThesaurus, and it will only return a result if "Wörterbuch" is spelled with a capital "W".

**Comment by phibr0** [comment]
Will be fixed in the new Release, I just added a Toggle for it.

![image](https://user-images.githubusercontent.com/59741989/132107587-29a93402-4c7d-4107-af0a-5c9726a72026.png)
