### ISSUE TITLE
Don’t the dictionary APIs support plural forms?

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#32]
I just ran across a valid, but _odd_ lookup: plural of "second" → "seconds" brought up odd-looking (at first glance) suggestions, and the lookup didn’t recognise the plural form:

![Knowledgebase - Obsidian v0 12 12_001](https://user-images.githubusercontent.com/3706922/128082424-4290adb3-f6bd-48d8-b661-17ae49150a08.png)

I’m sure the suggestion is valid (like in "I second that motion"), but it looks odd at the first glance.

Don’t the dictionary APIs support plural forms?

**Comment by phibr0** [comment]
To get better Results with the Synonym Popover you could enable the "Advanced Synonym Search", which then analyzes the whole sentence to find better words.

Maybe some API's don't support plural forms. It depends on the API and not on the Plugin, this isn't something I could do anything about
