### ISSUE TITLE
[ERROR] PT-BR dictionary returning an error

### ISSUE THREAD

**Issue by firinael** [phibr0/obsidian-dictionary#34]
Hi, doing anything with the Brazilian Portuguese (Português do Brasil) dictionary will return the following error:

![image](https://user-images.githubusercontent.com/67032657/129273553-c4d235ae-1472-491e-961b-3af91b933e21.png)

**Comment by phibr0** [comment]
The Error Message simply meant that there is no Definition for that word. It was pretty confusing so i already changed it
