### ISSUE TITLE
2.14.5: {{lang}} as RFC1766 value ("ru", "en-GB", "en-US")?

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#37]
`{{lang}}` in the filename prefix/suffix currently returns only the "…as spoken in" part of a RFC1766 language identifier, like `US`.

Could we please have return `{{lang}}` a complete RFC1766 language code, like `en-US`, `ru`, `pt-BR`?

This is the way the HTML `lang` attribute works, and so `{{lang}}` could directly be used with that (in the template, for instance).

**Comment by phibr0** [comment]
Could you provide the RFC1766 Values for the following languages?
```ts
export const LANGUAGES = {
    "en_US": "English (US)",
    "hi": "हिन्दी (Hindi)",
    "es": "Español (Spanish)",
    "fr": "Français (French)",
    "ja": "日本語 (Japanese)",
    "ru": "Русский (Russian)",
    "en_GB": "English (UK)",
    "de": "Deutsch (German)",
    "it": "Italiano (Italian)",
    "ko": "한국어 (Korean)",
    "pt_BR": "Português do Brasil (Brazilian Portuguese)",
    "ar": "اَلْعَرَبِيَّةُ‎ (Arabic)",
    "tr": "Türkçe (Turkish)",
    "cn": "中国人 (Chinese)"
}
```

**Comment by phibr0** [comment]
Or can I simply use what's on the left side? These are using an `_` though.

**Comment by Moonbase59** [comment]
Sure, just a sec, checking & writing a list …

export const LANGUAGES = {
    "en-US": "English (US)",
    "hi": "हिन्दी (Hindi)",
    "es": "Español (Spanish)",
    "fr": "Français (French)",
    "ja": "日本語 (Japanese)",
    "ru": "Русский (Russian)",
    "en-GB": "English (UK)",
    "de": "Deutsch (German)",
    "it": "Italiano (Italian)",
    "ko": "한국어 (Korean)",
    "pt-BR": "Português do Brasil (Brazilian Portuguese)",
    "ar": "اَلْعَرَبِيَّةُ‎ (Arabic)",
    "tr": "Türkçe (Turkish)",
    "cn": "中国人 (Chinese)"
}

Since some RFC (don’t ask ;-)) states "always try to use the most generic language code", I used these above. I also assume most dictionary providers do the same.

It _may_ be possible that some further distinction should be made with Japanese, Korean (South, North), and Chinese (different writing systems/language variants), but we’d have to check the dict providers and/or native speakers for that.

**Comment by Moonbase59** [comment]
You _are_ fast. Too bad it’s yet another table needed :-(

**Comment by phibr0** [comment]
Yeah, I could just edit the old one, but then I would have to also migrate all API's to the new Format again

**Comment by Moonbase59** [comment]
Thanks for letting us have this nice upgrade!
