### ISSUE TITLE
2.14.5: Make subfolders work with {{lang}} prefix

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#39]
It would be nice to be able to use _subfolders_ of the dictionary folder for different languages:

- Local Dictionary Folder: `Dictionary`
- Filename prefix: `{{lang}}/`
- Filename suffix: (empty)

Thus, we’d get something like

- `Dictionary/de`
- `Dictionary/en-US`
- `Dictionary/en-GB`

Currently, if trying this on "New Note", it shows a modal saying file exists (it did, in `Dictionary`). When I select "Yes, overwrite", instead of creating a new subfolder `en-US`, it _stays_ in the modal but seems to affect the synonym list beneath it (seems like clicking "through" the modal).

I’d have expected it
- to check for an existing entry in the (then non-existent) `Dictionary/en-US` folder,
  - probably show an error stating it doesn’t exist and ask for creation
- then simply create the subfolder `Dictionary/en-US` and put the new note there.

For people wishing for their Dictionaries named `Dictionary en-US` etc., it’d also be helpful to use `{{lang}}` in the Dictionary folder name.

Related: #37, #38

**Comment by phibr0** [comment]
I see what the Problem is, so you are currently using something like `{{lang}}/` as your Prefix right?

**Comment by Moonbase59** [comment]
I tried that, yes ;-) So we have all crazy options tested … (users are creative)

**Comment by Moonbase59** [comment]
But no objections against putting that in the Dictionary folder name  field, like `Dictionary/{{lang}}` so the prefix and suffix would stay reserved for _filename_ variations.

**Comment by phibr0** [comment]
I added a simple toggle to do that in the settings, but 

> But no objections against putting that in the Dictionary folder name field, like Dictionary/{{lang}} so the prefix and suffix would stay reserved for filename variations.

would have been even simpler.

**Comment by phibr0** [comment]
> I tried that, yes ;-) So we have all crazy options tested … (users are creative)

That would have worked as long as the Folder already existed. Now Folders that don't exist yet simply get created.
