### ISSUE TITLE
Clearer Icons

### ISSUE THREAD

**Issue by chetachiezikeuzor** [phibr0/obsidian-dictionary#4]
Hello! Firstly, WOW! I just want to thank you and @mgmeyers for this fantastic plugin. I work on writing assignments in Obsidian almost every day and this has been a lifesaver for me. I just wanted to highlight a small detail change, nothing crazy. The icons look a bit muddied while using certain themes. They're a bit hard to see, especially in a darker theme. So I think the icons would look better with a fill opacity of 0.0. I added a few screenshots to show this better. Thanks so much! :)

<img width="370" alt="Screen Shot 2021-05-28 at 4 30 24 PM" src="https://user-images.githubusercontent.com/79069364/120044082-bffd0680-bfd2-11eb-9141-1497e252147a.png">
<img width="370" alt="Screen Shot 2021-05-28 at 4 30 58 PM" src="https://user-images.githubusercontent.com/79069364/120044080-bf647000-bfd2-11eb-9a62-6b500bc2c1e5.png">

<img width="576" alt="Screen Shot 2021-05-28 at 4 36 49 PM" src="https://user-images.githubusercontent.com/79069364/120044174-ee7ae180-bfd2-11eb-8145-5979f4619414.png">

**Comment by phibr0** [comment]
Will fix that in the next Release
