### ISSUE TITLE
2.15.0: Protocol sometimes missing from audio link, making it unplayable

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#41]
Using 2.15.0, English (US), definition & synonym provider "Free Dictionary API", looking up, for instance "right hand", delivers an audio link that’s unplayable, both in pane and generated note, due to the protocol missing:

```
<source src="//ssl.gstatic.com/dictionary/static/sounds/20200429/right_hand--1_gb_1.4.mp3">
```

Manually adding the `https:` protocol makes it playable.

Since we might encounter APIs that _don’t_ use `https:`, it might be clever to check if the returned audio link _uses_ a protocol, if not, add the one used to make the request.

**Comment by phibr0** [comment]
I added a check for if the audio url contains the protocol, if not i will just add https:// for now, since the localdictionarybuilder doesn't have access to the apis and the FreeDictionaryAPI is the only one which actually provides audio

**Comment by Moonbase59** [comment]
Overdid it ;-) The protocol is just the `https:` part, the `//` were already in the resource URI, so now you generate

```html
<source src="https:////ssl.gstatic.com/dictionary/static/sounds/20200429/cheers--_gb_1.mp3">
```

(four `////`)

**Comment by phibr0** [comment]
Already fixed that again, but forgot to trigger the Release. Will do it when I'm back home.
