### ISSUE TITLE
FreeDictionaryAPI will stop supporting Languages other than English

### ISSUE THREAD

**Issue by phibr0** [phibr0/obsidian-dictionary#43]
See meetDeveloper/freeDictionaryAPI@e1a9c6c and https://github.com/meetDeveloper/freeDictionaryAPI/issues/102 for further reference.

**Comment by Moonbase59** [comment]
It’s a crux with FOSS at times: All the good stuff suddenly gets bought out and buried, or made payable; or the authors can’t or don’t want to work on it anymore.

The Free Dictionary API was a step in the right direction, I felt. Sad to see it go, for anything but English.

**Comment by meetDeveloper** [comment]
@Moonbase59 

With heavy heart I am taking this decision. I wanted to use data from somewhere where there is no problem to use the API for commercial usage. Free Dictionary API is being used in many projects and people always come up with questions regarding commercial usage. As Wiktionary is licensed in a way that I won't have any problems on legal side. That is why I took this decision. I have not yet removed other languages, just removed it from website and GitHub so that new users don't use API for other languages.

**Comment by phibr0** [comment]
> With heavy heart I am taking this decision. I wanted to use data from somewhere where there is no problem to use the API for commercial usage. Free Dictionary API is being used in many projects and people always come up with questions regarding commercial usage. As Wiktionary is licensed in a way that I won't have any problems on legal side. That is why I took this decision. I have not yet removed other languages, just removed it from website and GitHub so that new users don't use API for other languages.

Totally understand that! But why don't you provide the new Wiktionary API for more languages? I don't know about all of them but I tried the German one and it's pretty solid too!

**Comment by meetDeveloper** [comment]
What all languages you want? And can you check if all of them are very reputable on Wiktionary

**Comment by phibr0** [comment]
Hm. I don't know all of these languages myself so that might be pretty hard. I just want to get a replacement for the people who are using this Plugin. I of course also understand that this is a lot of work for you.

**Comment by phibr0** [comment]
I *think* most important would be, german, french, hindi, japanese, russian and spanish.

**Comment by Moonbase59** [comment]
@meetDeveloper Hey, thanks for stepping in here, much appreciated! I guess we do understand the reasons, and no small team or one-person-show can face legal issues with any of the "big ones".

Wiktionary might be good source, although maybe to much unstructured data to cleanly post-process?

In any case, maybe there can be some mutual benefit here. I feel a plugin like @phibr0’s should be able to rely on something good _upstream_, like the Free Dictionary API. Maybe there _could_ be a way of helping each other, resulting in keeping the actual Wiktionary lookup "hidden" and without the need to develop a similar Wiktionary API layer for the Obsidian Dictionary plugin?

**Comment by meetDeveloper** [comment]
@Moonbase59 @phibr0 

> Wiktionary might be good source, although maybe to much unstructured data to cleanly post-process?

I already have fetched 300,000 English words from Wiktionary and will coming weekend set the English language source to be Wiktionary. I have to once check how much Wiktionary can be relied upon for other languages.

> In any case, maybe there can be some mutual benefit here. I feel a plugin like @phibr0’s should be able to rely on something good upstream, like the Free Dictionary API. Maybe there could be a way of helping each other, resulting in keeping the actual Wiktionary lookup "hidden" and without the need to develop a similar Wiktionary API layer for the Obsidian Dictionary plugin?

Any changes in source will not affect any consumers as I will keep the response structure same so Obsidian Dictionary Plugin won't have to change in any way.

As I am only single person writing code for Dictionary API without much financial support, adding Wiktionary support for other languages might come later but I will meanwhile keep the other languages working as they are now. I have removed mention of other languages from Website and Github to avoid new users using API for languages other than English.

**Comment by phibr0** [comment]
That's nice to hear!

**Comment by ichmoimeyo** [comment]
HI

Have you checked out ...

https://yandex.com/dev/dictionary/

**Comment by Gentleman03** [comment]
Maybe it's possible to use Google Spell Check API?

https://serpapi.com/spell-check

**Comment by EhuddR** [comment]
Hey @phibr0! I hope you doing well. So, I was searching for an API for spanish language and suddenly this appears on my radar. Maybe can you use it for deffinitions of RAE (Real Academia Española de Lengua). I'm sorry but I have no experience with programming at all to make it work. 

👉 https://github.com/squat/drae**

**Comment by phibr0** [comment]
I added my own Implementation of a Google scraping mechanism, this should combat the loss of the free dictionary api a bit.
