### ISSUE TITLE
Franch : No synonym — Error

### ISSUE THREAD

**Issue by Mara-Li** [phibr0/obsidian-dictionary#44]
No synonyms are showing in French, using Synonymo :
![image](https://user-images.githubusercontent.com/30244939/130222128-010834be-ae41-499a-90e3-cd4c0592ed73.png)

Altervista work as excepted.

**Comment by phibr0** [comment]
Could you try disabling the Advanced Synonym Search?

**Comment by phibr0** [comment]
Synonymo is redirecting after visiting their Page now which confuses fetch and request. As for French there is still Altervista available I will just disable Synonymo for the time being.
