### ISSUE TITLE
Missing to type http in audio link make it unusable

### ISSUE THREAD

**Issue by Archie-2021** [phibr0/obsidian-dictionary#45]
I couldnt play pronunciations. I thought it is a problem with using proxy but i noticed the link is something like this //ssl.gstatic.com instead of https://ssl which works fine as I tested it. Please fix that misstyping. I can fix it manually in notes but it is not usable in side pane.

Thanks

**Comment by phibr0** [comment]
This should have been fixed in the latest Release. Are you not on the latest Version?

If you are, could you provide a Screenshot of the html in the Dev Tools of the audio element?

**Comment by Archie-2021** [comment]
Yes. after sending this issue and updated it and it is fixed now. Thanks
