### ISSUE TITLE
Change default language based on YAML data

### ISSUE THREAD

**Issue by xplosionmind** [phibr0/obsidian-dictionary#49]
### Describe the feature

As I understand, currently this plugin could automatically switch languages based on folders. Nevertheless, I have notes in Italian, English and French placed everywhere in every folder of my vault.

What I would like to have is for the plugin to read the `lang:` parameter in YAML and consequently set the language for that note.

For example:

```yaml
lang: it
```

would set the language of the page in Italian.

Furthermore, it should be possible to set a default language, so that if `lang: ` is not specified, it is the one chosen to be the main one.

### Does this fix a problem? If so, specify.

—

### Did you consider other alternatives?

Right now I am using the plugin for English notes only.

### Screenshots and recordings

Current folder setup, to which the YAML setup should be added:
<img width="904" alt="Screenshot 2021-09-05 at 5 35 53 PM" src="https://user-images.githubusercontent.com/42862428/132132648-0a31792c-4971-4f34-a64d-493b4910a7a6.png">

**Comment by phibr0** [comment]
I understand your Requests, but you have to remember that on changing the Language the User might also need to change their API Provider (because one might not be available in that language). How would that work?

**Comment by xplosionmind** [comment]
> How would that work?

There is no better solution, so I guess it would!

**Comment by phibr0** [comment]
Would you be fine with using the Values on the left side as the Language Codes for the `lang` attribute?

```
export const LANGUAGES = {
    "en_US": "English (US)",
    "hi": "हिन्दी (Hindi)",
    "es": "Español (Spanish)",
    "fr": "Français (French)",
    "ja": "日本語 (Japanese)",
    "ru": "Русский (Russian)",
    "en_GB": "English (UK)",
    "de": "Deutsch (German)",
    "it": "Italiano (Italian)",
    "ko": "한국어 (Korean)",
    "pt_BR": "Português do Brasil (Brazilian Portuguese)",
    "ar": "اَلْعَرَبِيَّةُ‎ (Arabic)",
    "tr": "Türkçe (Turkish)",
    "cn": "中国人 (Chinese)"
}
```

**Comment by xplosionmind** [comment]
Perfect! This is what I am using.

For English I am just using `en`, but that I would choose it as default lang.

Thanks a lot!
