### ISSUE TITLE
[Bug]: The plugin is causing obsidian to show a black screen on launching

### ISSUE THREAD

**Issue by zFrostz** [phibr0/obsidian-dictionary#51]
### Describe the bug

The recent update to the plugin might have caused some issue with the workspace file or the workspaces json file in the .obsidian folder since after installing the update 2.16.5 obsidian just shows a black screen after launching. 

### Steps to reproduce

1. Install update 2.16.5 
2. Relaunch obsidian
3. Loading is complete but nothing shows up on the screen

### Operating system

Windows

**Comment by phibr0** [comment]
I cannot reproduce this behavior. Which Obsidian Version are you on?

Please press ` CTRL + SHIFT + I` while starting Obsidian to open the Developer Console and navigate to Console and look for errors, send them here.

**After that:**

This Plugin doesn't (or shouldn't) touch any configuration files, except the ones inside the plugins' folder.

How come that you think the workspace file is corrupted? Can you send it here? Its located under `.obsidian/workspace`. You could also try deleting it to regenerate it. If you cannot disable this Plugin because of the Blackscreen, please try to delete it in the Plugin folder. `.obsidian/plugins/dictionary-plugin`

**Comment by zFrostz** [comment]
I am sorry for reaching out to you this late, I almost forgot about this subject. I did some more experimentation and it looks like the plugin is causing it somewhat indirectly. I noticed that turning on the plugin while obsidian was fully booted up caused no problems but If I tried to change to a different workspace using the workspaces plugin it caused the same problem as mentioned. I tried to delete all my workspaces and recreate them with a different name but it seemed to work only in some cases. However when I switch to a workspace when I have the plugin turned off it works just fine. The problem happens only when I do it on workspaces that contain the dictionary pane. So my guess is the new version might be conflicting with the old workspace templates in some way maybe? 

Here's the workspaces file as you asked...

[Workspaces.zip](https://github.com/phibr0/obsidian-dictionary/files/7154081/Workspaces.zip)

Github isn't allowing json files so I had to zip them first

**Comment by Ramanathan10** [comment]
Yep, facing the same issue. The plug-in does not even display the search results either. Using 1.0.4 of Obsidian on iPad OS 15 beta

**Comment by zFrostz** [comment]
> Yep, facing the same issue. The plug-in does not even display the search results either. Using 1.0.4 of Obsidian on iPad OS 15 beta

Its such a relief to see that I am not the only one facing this issue. Thank you for confirming that and adding your experience to the discussion

**Comment by zFrostz** [comment]
I think the new 2.18.0 update has fixed this issue now however I didn't see a mention of it in the changelog but I haven't encountered the problem again since I updated to 2.18.1 this morning. Plus the search results display problem mentioned by @Ramanathan10 is fixed as well. So I would close this issue now.

Thank you very much for your help! Also for building this amazing plugin which has become an indispensable part of my obsidian workflow. Best of luck to you for the future of this plugin
