### ISSUE TITLE
More options for new note creation

### ISSUE THREAD

**Issue by Archie-2021** [phibr0/obsidian-dictionary#52]
Currently, when hitting new note button. It creates the note and opens it in a new tab. I want to have the option to open it in current tab or not open it at all and just creat the note. Opening a new tab messes with my tabs size configuration for some reason. 

Thanks

**Comment by phibr0** [comment]
If you hold `ctrl` while generating the Note it won't be opened now.

**Comment by Archie-2021** [comment]
Thank you
