### ISSUE TITLE
[Bug]: Latest release tagged incorrectly

### ISSUE THREAD

**Issue by ScottKillen** [phibr0/obsidian-dictionary#53]
### Describe the bug

The latest release should have been tagged 2.17.5, but it was tagged 1.17.5. This has broken the plugin's automatic updates in Obsidian. It must be manually updated.

### Relevant errors (if available)

```shell
https://github.com/phibr0/obsidian-dictionary/releases/download/2.17.5/manifest.json
Failed to load resource: the server responded with a status of 404 ()
```

### Steps to reproduce

Click the plugin's update button in Obsidian's list of community plugins.

### Expected Behavior

The update will install correctly.

### Operating system

Windows

**Comment by phibr0** [comment]
Should work now

**Comment by ScottKillen** [comment]
✔️ It does!
