### ISSUE TITLE
[Bug]: It never finds anything in spanish and VERY limited in english

### ISSUE THREAD

**Issue by alanalvarado** [phibr0/obsidian-dictionary#66]
### Describe the bug

MAC OSX Monterrey with last public available obsidian

I set the frontmatter to english or spanish, when I try to find a word, it never finds anything.

### Steps to reproduce

try to search any word with the command palette or directly in the dictionary tab.

### Expected Behavior

Find the meaning of words

### Language

es

### Operating system

macOS

**Comment by phibr0** [comment]
Unfortunately there isn't much I can do about that, except maybe removing other languages soon.. 
See #43 for more information

**Comment by phibr0** [comment]
There aren't many API's providing definitions and synonyms that are free.

**Comment by phibr0** [comment]
I added a **experimental** version of my own google scraper mechanism. This should help a bit in both cases. Select Google as a Definition and Synonym Provider in the Settings.

**Comment by alanalvarado** [comment]
Thank you very much, I will check it out, btw what about OpenAI API
