### ISSUE TITLE
request: multilingual support

### ISSUE THREAD

**Issue by firinael** [phibr0/obsidian-dictionary#8]
I'd use this plugin super often if it supported either:

- On-the-fly language switching (command palette/hotkey/UI element)
- Having multiple dictionaries active at once

Having either of those would make it wonderful!

**Comment by phibr0** [comment]
I agree, this would make the Plugin even more useful. I will think about how I am going to implement this. Personally I would like the Plugin to detect the Language of a Word automatically, but this is probably not feasible.. A UI Element would be more feasible, but even this would need a rewrite of how the different API choices are handled.

**Comment by phibr0** [comment]
Hey! I added a Modal you can open via hotkey/command palette to change the Language (and in future with more API's even the applicable API's) 
This will most likely be improved in the Future too, but for now this is a workaround.

Do you think I can close this Issue for now?
