### ISSUE TITLE
Support Ukrainian language... before it's too late!

### ISSUE THREAD

**Issue by bmorphism** [phibr0/obsidian-dictionary#80]
### Describe the feature

Ukrainian i18n translation _and_ incentives that make it likely to happen.

### Does this fix a problem? If so, specify.

It will make the cosmic injustice of having a Russian translation and _not_ a Ukrainian go away.

### Did you consider other alternatives?

I considered Belarussian but it wasn't there either!

### Screenshots and recordings

https://www.youtube.com/watch?v=5MhKWLCIwD8 Slava Ukrajini! 🫡🏴

**Comment by phibr0** [comment]
As I don't know these languages myself, they have to be community contributed. If you are able to provide a Ukrainian Translation, take a look here: https://github.com/phibr0/obsidian-dictionary#translations
