### ISSUE TITLE
request: option to edit the template for new notes

### ISSUE THREAD

**Issue by AngelusDomini** [phibr0/obsidian-dictionary#9]
The New Note feature of this plugin works well with a particular use-case of mine, so I appreciate it, but it seems that the template for it can't be edited. I'm hoping that you would allow editing of the template perhaps via the options, like what you see in the Note Refactor plugin.

Similarly, maybe also have the option to change the default file name, like perhaps the user wants to automatically add an emoji or something like that, or the option to have the word's first letter to be capitalized (as it currently is) or not (what I personally prefer).

Hope these are doable and easy to implement, don't want this simple request to cause too much trouble on your part. Thank you so much for what you do!

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/120919246-e00a8500-c6b8-11eb-9359-3525bfc1a6ef.png)
Is this what you need?

**Comment by phibr0** [comment]
Hey!
I added the Features you requested and they were just released in Version 2.6.0!

**Comment by AngelusDomini** [comment]
Yes, that's great!
And wow that was fast, tested it just now and so far seems to work really well. Looks like I didn't cause you too much trouble c:
Thank you so much, I really appreciate it! 🙏

**Comment by AngelusDomini** [comment]
Ah, one comment if you don't mind, it's nit picky tho lol

Even with the capitalize file name option turned off, the title of the {{word}} in the note itself is still capitalized. Sorry for not mentioning this beforehand 🙏

The purpose of this is to differentiate between proper and common nouns, where most of the nouns from the dictionary are common nouns (hence why I prefer the titles to be lowercase). It can also be a distinction from these dictionary notes from my other terminology-based evergreen notes in Obsidian, where the latter would be capitalized.

Personally, I can just replace {{word}} from the template with Templater's `< %tp.file.title% >` function, and that would do. But perhaps some users may want want to use the suffix/prefix feature plus have a lowercase {{word}} title in the note and/or don't use Templater, but I'm not sure if there will be any.

Anyway, just thought I'd let you know. It's totally up to you if you want to implement it (it seems it won't be much trouble to do so anyway lol). Thank you once again :)

**Comment by phibr0** [comment]
Fixed!
